---
# Portworx Sharedv4 StorageClass
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-gitlab-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  io_profile: auto
allowVolumeExpansion: true
